### PR TITLE
Added Search bar on Main Screen

### PR DESCRIPTION
**Pull request by InsanelyHarsh**

### CODE REVIEW

**Comment by InsanelyHarsh** [comment]
Hi @aarish21 
I have completed both tasks. Can you approve both PRs after reviewing them, I need PRs for Hacktoberfest.
Thanks 🙂

**Comment by aarish21** [comment]
> Hi @aarish21
> I have completed both tasks. Can you approve both PRs after reviewing them, I need PRs for Hacktoberfest.
> Thanks 🙂
@InsanelyHarsh 
image
can you check out this error

**Comment by InsanelyHarsh** [comment]
@aarish21 on 134 line 
let searchResult:[**any** ContentList]
not let searchResult:[**Any** ContentList]
I checked in my repo that I Pushed there is any.

**Comment by aarish21** [comment]
> @aarish21 on 134 line
> let searchResult:[**any** ContentList]
> not let searchResult:[**Any** ContentList]
> I checked in my repo that is Pushed there is any.

still giving same error

**Comment by InsanelyHarsh** [comment]
Let me check and push the new version.

> > @aarish21 on 134 line
> > let searchResult:[**any** ContentList]
> > not let searchResult:[**Any** ContentList]
> > I checked in my repo that is Pushed there is any.
> 
> still giving same error

**Pull request closed without merging**
